# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-17 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyowner',
            name='car',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='keyowner',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
